### ISSUE TITLE
stop() async handling

### ISSUE THREAD

**Issue by stefanheine** [thenativeweb/runfork#1]
Hi, I realized that the stop() call doesn't stop the child process, but only sends a SIGINT signal once. there are situations when a process needs multiple SIGINT signals, or even a SIGTERM to go down.

I want to rely on the stop() call to really stop the child process and have implemented a check, retry, and finally fallback to SIGTERM mechanism. but to make use of this, the stop() call must be async.

now I wonder if you still want this as a pull request - even if it's breaking the current api (well, not really, as you can still call the async function without caring for the fact that it's async) - or if you would rather recommend to fork.

**Comment by goloroden** [comment]
Implemented in `1.0.0`.
